if (self.CavalryLogger) { CavalryLogger.start_js(["mhVSm"]); }

__d("AdsBugReportHideDialogDataReducerPlugin",[],(function(a,b,c,d,e,f){"use strict";a={reduce:function(a,b){return{bugReportProps:null,isShown:!1}}};e.exports=a}),null);
__d("AdsBugReportProviderPlugin",[],(function(a,b,c,d,e,f){"use strict";a={initialState:{bugReportProps:null,isShown:!1}};e.exports=a}),null);
__d("AdsBugReportProvider",["Laminar","AdsBugReportProviderPlugin"],(function(a,b,c,d,e,f){"use strict";e.exports=b("Laminar").__createProvider(b("AdsBugReportProviderPlugin"),"AdsBugReportProviderPlugin")}),null);
__d("AdsBugReportHideDialogDataAction",["Laminar","AdsBugReportHideDialogDataReducerPlugin","AdsBugReportProvider"],(function(a,b,c,d,e,f){"use strict";a=b("Laminar").__createAction(function(){return[b("Laminar").__createReducer(b("AdsBugReportHideDialogDataReducerPlugin"),b("AdsBugReportProvider"),{})]},function(){return[]},"BUG_REPORT.HIDE_DIALOG");e.exports=a}),null);
__d("AdsVideoPickerShouldOpenOnErrorToastCardClickCTAReducerPlugin",[],(function(a,b,c,d,e,f){"use strict";a={reduce:function(a,b){return b.data.isErrorVideoToastCard===!0?babelHelpers["extends"]({},a,{shouldOpenPicker:!0}):a}};e.exports=a}),null);
__d("AdsVideoToastCardsClickCTAReducerPlugin",["AdsVideoUploadToastCardUtils"],(function(a,b,c,d,e,f){"use strict";a={reduce:function(a,c){return b("AdsVideoUploadToastCardUtils").dismissVideoToastCardByCTA(a,c)}};e.exports=a}),null);
__d("AdsVideoToastCardsClickCTADataAction",["Laminar","AdsVideoPickerShouldOpenOnErrorToastCardClickCTAReducerPlugin","AdsVideoPickerUIDataProvider","AdsVideoToastCardsClickCTAReducerPlugin","AdsToastCardDataProvider"],(function(a,b,c,d,e,f){"use strict";a=b("Laminar").__createAction(function(){return[b("Laminar").__createReducer(b("AdsVideoPickerShouldOpenOnErrorToastCardClickCTAReducerPlugin"),b("AdsVideoPickerUIDataProvider"),{}),b("Laminar").__createReducer(b("AdsVideoToastCardsClickCTAReducerPlugin"),b("AdsToastCardDataProvider"),{})]},function(){return[]},"VIDEO.TOAST_CARDS_CLICK_CTA");e.exports=a}),null);
__d("AdsBugReportContainer.react",["AdsBugReportHideDialogDataAction","AdsBugReportProvider","AdsFluxContainer","BootloadOnRender.react","JSResource","LazyComponent.react","React","ReactFragment"],(function(a,b,c,d,e,f){"use strict";__p&&__p();a=function(a){__p&&__p();babelHelpers.inheritsLoose(c,a);function c(){return a.apply(this,arguments)||this}c.getStores=function(){return[b("AdsBugReportProvider").toFluxStore()]};c.calculateState=function(){return babelHelpers["extends"]({},b("AdsBugReportProvider").toFluxStore().getState())};var d=c.prototype;d.render=function(){return b("React").createElement("span",null,this.renderLayers())};d.renderLayers=function(){return b("ReactFragment").create({dialog:this.state.isShown?this.$1():null})};d.$1=function(){var a=babelHelpers["extends"]({},this.state.bugReportProps,{onToggle:this.$2});return b("React").createElement(b("BootloadOnRender.react"),{component:b("React").createElement(b("LazyComponent.react"),a),loader:b("JSResource")("BugReport.ads").__setRef("AdsBugReportContainer.react"),placeholder:b("React").createElement("div",null)})};d.$2=function(a){a||b("AdsBugReportHideDialogDataAction").dispatch({},{line:"65",module:"AdsBugReportContainer.react.js"})};return c}(b("React").Component);e.exports=b("AdsFluxContainer").create(a,{pure:!1,name:e.id})}),null);